### ISSUE TITLE
Double encoding of rfc822's text parts with utf-8 charset and Content-Transfer-Encoding 8bit

### ISSUE THREAD

**Issue by azulli** [Enough-Software/enough_mail#138] opened 2021-03-29 18:07 UTC
Hi,
I've stumbled upon a double encoding issue trying to get a text from a message/rfc822 attachment.
This specific attachment has a text/plain part in utf-8 and content-transfer-encoding 8bit so no encoding was performed by the server.
To access the contents of the attached message I usually do a

```dart
var fetchId = ...
var msg = MimeMessage.parseFromText(email.getPart(fetchId)!.decodeContentText());
```

Now, if i try to get the text content with either `decodeTextPlainPart()` or `decodeContentText()` all non ASCII characters are encoded again.
So, instead of a text like "Emäįl heading" what I obtain is "EmÃ¤Ä¯l heading".

For now I'm forcing a decoding when the retrieved text contains a 0xC3 character byte, but it's a hack.

Anyway, keep up the good work.
Regards.

**Comment by robert-virkus** [comment] 2021-03-29 21:11
Thanks for the report, I think it should become easier to get an embedded rfc 822 message. Can you post the full code of a problematic mime message that contains a rfc822 part? Please ensure to remove any private info from it, though.

**Comment by azulli** [comment] 2021-03-30 08:07
Absolutely.
Here is a redacted sample email that shows the issue:
[example-email.eml.txt](https://github.com/Enough-Software/enough_mail/files/6227412/example-email.eml.txt)

**Comment by robert-virkus** [comment] 2021-04-06 13:27
hi again, with this mesage I cannot reproduce the stated problem, I guess it's because the embedded rfc822 message is using UTF-8 codec. Do you have this problem also with the given sample email?

**Comment by azulli** [comment] 2021-04-06 17:35
Hi, the sample is composed as closest as possible to the original email.
Maybe the issue pops out fetching it from an imap server, but not when loaded from file. I should test it 🤔.

**Comment by azulli** [comment] 2021-04-07 09:55
I'd worked on a test case that can show the issue (attached here).
As detailed into the code (lengthy, forgive me) this behavior shows when the message is fetched as binary instead of text.
Don't know why, all message from the IMAP server with which I'm working are translated into `BinaryMimeData` instances.
[doubleenc_test.dart.txt](https://github.com/Enough-Software/enough_mail/files/6270645/doubleenc_test.dart.txt)

**Comment by robert-virkus** [comment] 2021-04-07 10:20
Thanks again, I have come up with a different approach to simulate the problem and just pushed a potential fix, Can you test this out? If it does not, I will try to replicate it with your new sample message.

**Comment by azulli** [comment] 2021-04-07 12:53
Thanks a lot! The issue is resolved in the test case.
I'll merge the latest commits into my fork and we'll see how it performs.

**Comment by robert-virkus** [comment] 2021-04-07 13:07
Glad to hear it. Closing it for now, please re-open in case there are additional problems.

**Closed by robert-virkus** 2021-04-07 13:07 UTC
Labels: enhancement, mime
