### ISSUE TITLE
error  in quoted_printable_mail_codec.dart

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#65] opened 2020-06-03 14:07 UTC
enough_mail-0.0.21/lib/codecs/quoted_printable_mail_codec.dart

error invalid number(150

**row 118: correct**
 try {
            var decoded = codec.decode(charCodes);
            buffer.write(decoded);
          } catch (e) {}

**Comment by robert-virkus** [comment] 2020-06-03 19:41
Hm, I am unsure if we should just silently fail to decode in this case. Do you have input that fails? Maybe it is possible to fix the root cause....

**Comment by robert-virkus** [comment] 2020-08-09 09:27
Closing this for now

**Closed by robert-virkus** 2020-08-09 09:27 UTC
Labels: bug, mime
